import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogClose
} from "@/components/ui/dialog"

import { Button } from "@/components/ui/button"
import { useTask } from "@/context/TaskContext"

const TaskAISuggestionDialog = () => {

  const {
    aiSuggestion,
    isAISuggestionDialogOpen,
    setIsAISuggestionDialogOpen,
    handleCreateTaskSuggestedByAI
  } = useTask()

  return (
    <Dialog open={isAISuggestionDialogOpen}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>AI Suggestion</DialogTitle>
          <DialogDescription className="text-sm text-slate-500">
            Bellow is the suggestion generated by AI for the next task.
          </DialogDescription>
        </DialogHeader>
        <div className="flex items-center space-x-2">
          <div className="p-4 rounded-md bg-slate-50">
            <p>{ aiSuggestion }</p>
          </div>
        </div>
        <DialogFooter className="sm:justify-start">
          <DialogClose asChild>
            <div className="w-full flex space-x-2 justify-end">
              <Button
                className='cursor-pointer'
                variant="ghost"
                onClick={() => setIsAISuggestionDialogOpen(false)}
              >
                Cancel
              </Button>
              <Button className='bg-green-600 cursor-pointer' onClick={handleCreateTaskSuggestedByAI}>
                Use AI Suggestion
              </Button>
            </div>
          </DialogClose>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

export default TaskAISuggestionDialog