import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogClose
} from "@/components/ui/dialog"


import { Button } from "@/components/ui/button"
import { useTask } from "@/context/TaskContext"

const TaskAISuggestionDialog = () => {

  const {
    aiSuggestion,
    isAISuggestionDialogOpen,
    handleCreateTaskSuggestedByAI
  } = useTask()

  return (
    <Dialog open={isAISuggestionDialogOpen}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>AI Suggestion</DialogTitle>
          <DialogDescription>
            Bellow is the suggestion generated by AI for the next task.
          </DialogDescription>
        </DialogHeader>
        <div className="flex items-center space-x-2">
          <div className="grid flex-1 gap-4">
            <p>{ aiSuggestion }</p>
          </div>
        </div>
        <DialogFooter className="sm:justify-start">
          <DialogClose asChild>
            <Button className='bg-green-600 cursor-pointer' onClick={handleCreateTaskSuggestedByAI}>
              Create Suggested Task
            </Button>
          </DialogClose>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

export default TaskAISuggestionDialog